# librerías
library(tidyverse)
library(haven)
library(ggplot2)
library(lubridate)
library(lmtest)
library(kableExtra)
library(wesanderson)
library(corrr)
library(ggcorrplot)
library(readxl)
library(ggtext)
library(magic)
library(zoo)
library(stargazer)
library(fastDummies)
